# Generated by Claude Code on 2025-11-15

import django.db.models.deletion
import judge.models.interface
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('judge', '0213_add_rate_disqualified'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(
                    db_index=True,
                    help_text='Custom short URL identifier (max 30 characters, letters/numbers/dash/underscore only)',
                    max_length=30,
                    unique=True,
                    validators=[judge.models.interface.validate_short_code],
                    verbose_name='short code',
                )),
                ('long_url', models.URLField(
                    help_text='The full URL to redirect to',
                    max_length=2000,
                    verbose_name='destination URL',
                )),
                ('description', models.TextField(
                    blank=True,
                    help_text='Optional description or notes about this URL',
                    verbose_name='description',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('click_count', models.IntegerField(
                    default=0,
                    help_text='Number of times this short URL has been accessed',
                    verbose_name='click count',
                )),
                ('last_accessed', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='last accessed',
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Inactive URLs will return 404',
                    verbose_name='active',
                )),
                ('creator', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='shortened_urls',
                    to='judge.profile',
                    verbose_name='creator',
                )),
                ('organization', models.ForeignKey(
                    blank=True,
                    help_text='Optional: Associate this URL with an organization',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='shortened_urls',
                    to='judge.organization',
                    verbose_name='organization',
                )),
                ('site', models.ForeignKey(
                    default=settings.SITE_ID,
                    help_text='Site/domain where this short URL is active',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='sites.site',
                    verbose_name='site',
                )),
            ],
            options={
                'verbose_name': 'URL shortener',
                'verbose_name_plural': 'URL shorteners',
                'ordering': ['-created_at'],
                'permissions': (
                    ('create_url_shortener', 'Can create shortened URLs'),
                    ('view_all_url_stats', 'Can view all URL statistics'),
                ),
            },
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['short_code', 'site'], name='judge_urlsh_short_c_idx'),
        ),
        migrations.AddIndex(
            model_name='urlshortener',
            index=models.Index(fields=['creator', '-created_at'], name='judge_urlsh_creator_idx'),
        ),
    ]
